language: node_js
node_js:
  - "10"
install:
  - npm install -g cross-env tape standard
branches:
  only:
  - master
  - development
script:
  - npm run lint
  - npm test
cache:
  directories:
  - "node_modules"
